<a href="https://colab.research.google.com/github/R4y-4bsolut/Sample-ETL-Process/blob/main/ETL_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Import libraries

In [1]:
import pandas as pd

## 2. Extract Data

### 2.1. Enrollies Data - Google Docs

In [2]:
gg_sheet_id = '1VCkHwBjJGRJ21asd9pxW4_0z2PWuKhbLR3gUHm-p4GI'
url = 'https://docs.google.com/spreadsheets/d/' + gg_sheet_id + '/export?format=xlsx'
enrollies_data = pd.read_excel(url, sheet_name='enrollies')

In [3]:
enrollies_data

       enrollee_id        full_name      city gender
0             8949       Mike Jones  city_103   Male
1            29725      Laura Jones   city_40   Male
2            11561     David Miller   city_21    NaN
3            33241      Laura Davis  city_115    NaN
4              666    Alex Martinez  city_162   Male
...            ...              ...       ...    ...
19153         7386      Sarah Brown  city_173   Male
19154        31398    David Johnson  city_103   Male
19155        24576  Chris Hernandez  city_103   Male
19156         5756     Mike Johnson   city_65   Male
19157        23834       John Smith   city_67    NaN

[19158 rows x 4 columns]

### 2.2. Enrollies' Education - Excel file

In [6]:
enrollies_edu = pd.read_excel('/content/enrollies_education.xlsx')

In [7]:
enrollies_edu

       enrollee_id enrolled_university education_level major_discipline
0             8949       no_enrollment        Graduate             STEM
1            29725       no_enrollment        Graduate             STEM
2            11561    Full time course        Graduate             STEM
3            33241                 NaN        Graduate  Business Degree
4              666       no_enrollment         Masters             STEM
...            ...                 ...             ...              ...
19153         7386       no_enrollment        Graduate       Humanities
19154        31398       no_enrollment        Graduate             STEM
19155        24576       no_enrollment        Graduate             STEM
19156         5756       no_enrollment     High School              NaN
19157        23834       no_enrollment  Primary School              NaN

[19158 rows x 4 columns]

### 2.3. Enrollies Working Experience - CSV file

In [8]:
enrollies_working_exp = pd.read_csv('https://assets.swisscoding.edu.vn/company_course/work_experience.csv')

In [9]:
enrollies_working_exp

,enrollee_id,relevent_experience,experience,company_size,company_type,last_new_job
0,8949,Has relevent experience,>20,NaN,NaN,1
1,29725,No relevent experience,15,50-99,Pvt Ltd,>4
2,11561,No relevent experience,5,NaN,NaN,never
3,33241,No relevent experience,<1,NaN,Pvt Ltd,never
4,666,Has relevent experience,>20,50-99,Funded Startup,4
...,...,...,...,...,...,...
19153,7386,No relevent experience,14,NaN,NaN,1
19154,31398,Has relevent experience,14,NaN,NaN,4
19155,24576,Has relevent experience,>20,50-99,Pvt Ltd,4
19156,5756,Has relevent experience,<1,500-999,Pvt Ltd,2
19157,23834,No relevent experience,2,NaN,NaN,1

### 2.4. Training Hours - SQL database

In [10]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 3.6 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [11]:
from sqlalchemy import create_engine
import pymysql

In [12]:
engine = create_engine('mysql+pymysql://etl_practice:550814@112.213.86.31:3360/company_course')
training_hours = pd.read_sql_table('training_hours', con=engine)

In [13]:
training_hours.head()

   enrollee_id  training_hours
0         8949              36
1        29725              47
2        11561              83
3        33241              52
4          666               8

### 2.5. City Development Index (CDI) - Website

In [14]:
tables = pd.read_html('https://sca-programming-school.github.io/city_development_index/index.html')

In [15]:
cities = tables[0]

In [16]:
cities.head(5)

       City  City Development Index
0  city_103                   0.920
1   city_40                   0.776
2   city_21                   0.624
3  city_115                   0.789
4  city_162                   0.767

### 2.6. Employment - MySQL database

In [17]:
engine = create_engine('mysql+pymysql://etl_practice:550814@112.213.86.31:3360/company_course')
training_hours = pd.read_sql_table('employment', con=engine)

In [18]:
employment = pd.read_sql_table('employment', con=engine)

## Transform Data

### 3.1. Enrollies Data Table Transform

In [19]:
enrollies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   full_name    19158 non-null  object
 2   city         19158 non-null  object
 3   gender       14650 non-null  object
dtypes: int64(1), object(3)
memory usage: 598.8+ KB

In [20]:
enrollies_data['gender'] = enrollies_data['gender'].fillna(enrollies_data['gender'].mode()[0])

In [21]:
enrollies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   full_name    19158 non-null  object
 2   city         19158 non-null  object
 3   gender       19158 non-null  object
dtypes: int64(1), object(3)
memory usage: 598.8+ KB

In [22]:
enrollies_data['full_name'] = enrollies_data['full_name'].astype('string')

In [23]:
enrollies_data[['city', 'gender']] = enrollies_data[['city', 'gender']].astype('category')

In [24]:
enrollies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   full_name    19158 non-null  string
 2   city         19158 non-null  category
 3   gender       19158 non-null  category
dtypes: category(2), int64(1), string(1)
memory usage: 342.1 KB

### 3.2. Enrollies' Education Table Transform

In [25]:
enrollies_edu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   enrolled_university  18772 non-null  object
 2   education_level      18698 non-null  object
 3   major_discipline     16345 non-null  object
dtypes: int64(1), object(3)
memory usage: 598.8+ KB

In [26]:
enrollies_edu['enrolled_university'] = enrollies_edu['enrolled_university'].fillna(enrollies_edu['enrolled_university'].mode()[0])

In [27]:
enrollies_edu['education_level'] = enrollies_edu['education_level'].fillna(enrollies_edu['education_level'].mode()[0])

In [28]:
enrollies_edu['major_discipline'] = enrollies_edu['major_discipline'].fillna(enrollies_edu['major_discipline'].mode()[0])

In [29]:
enrollies_edu[['enrolled_university', 'education_level', 'major_discipline']] = enrollies_edu[['enrolled_university', 'education_level', 'major_discipline']].astype('category')

In [30]:
enrollies_edu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   enrolled_university  19158 non-null  category
 2   education_level      19158 non-null  category
 3   major_discipline     19158 non-null  category
dtypes: category(3), int64(1)
memory usage: 206.5 KB

### 3.3. Enrollies' Working Experience Table Transform

In [31]:
enrollies_working_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   relevent_experience  19158 non-null  object
 2   experience           19093 non-null  object
 3   company_size         13220 non-null  object
 4   company_type         13018 non-null  object
 5   last_new_job         18735 non-null  object
dtypes: int64(1), object(5)
memory usage: 898.2+ KB

In [32]:
enrollies_working_exp['experience'] = enrollies_working_exp['experience'].fillna(enrollies_working_exp['experience'].mode()[0])

In [33]:
enrollies_working_exp['company_size'] = enrollies_working_exp['company_size'].fillna(enrollies_working_exp['company_size'].mode()[0])

In [34]:
enrollies_working_exp['company_type'] = enrollies_working_exp['company_type'].fillna(enrollies_working_exp['company_type'].mode()[0])

In [35]:
enrollies_working_exp['last_new_job'] = enrollies_working_exp['last_new_job'].fillna(enrollies_working_exp['last_new_job'].mode()[0])

In [36]:
enrollies_working_exp[['relevent_experience', 'experience', 'company_size', 'company_type', 'last_new_job']] = enrollies_working_exp[['relevent_experience', 'experience', 'company_size', 'company_type', 'last_new_job']].astype('category')

In [37]:
enrollies_working_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   relevent_experience  19158 non-null  category
 2   experience           19158 non-null  category
 3   company_size         19158 non-null  category
 4   company_type         19158 non-null  category
 5   last_new_job         19158 non-null  category
dtypes: category(5), int64(1)
memory usage: 245.0 KB

## 4. Load Data

In [40]:
from sqlalchemy import create_engine

db_path = 'data_warehouse.db'
engine = create_engine(f'sqlite:///{db_path}')
enrollies_data.to_sql('Dim_Enrollies', engine, if_exists='replace', index=False)
enrollies_edu.to_sql('Dim_Enrollies_Education', engine, if_exists='replace' , index=False)
enrollies_working_exp.to_sql('Dim_Work_Experience', engine, if_exists='replace', index=False)
training_hours.to_sql('Dim_Training_Hours', engine, if_exists='replace', index=False)
cities.to_sql('Dim_Cities', engine, if_exists='replace', index=False)
employment.to_sql('Fact_Employment', engine, if_exists='replace', index=False)

19158